name: Apply
on:
  push:
    branches:
    - 'main'

permissions:
  id-token: write
  contents: read  

env:
  TF_VERSION: '1.5.7'
  TG_VERSION: 'v0.58.2'

jobs:
  detect-folders:
    runs-on: ubuntu-latest
    name: Detect folders to apply
    outputs:
      matrix: ${{ steps.detect-folders.outputs.all_changed_files }}'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get all changed directories into matrix
        id: detect-folders
        uses: tj-actions/changed-files@v44
        with:
          dir_names: 'true'
          matrix: 'true'
          files: |
             **.tf*
      
      - name: List all changed folders
        run: echo '${{ steps.detect-folders.outputs.all_changed_files }}'

  terraform-apply:
    name: Terraform apply
    runs-on: ubuntu-latest
    if: needs.detect-folders.outputs.matrix != '[]'
    needs: detect-folders
    strategy:
      fail-fast: false
      matrix:
        dirs: ${{ fromJSON(needs.detect-folders.outputs.matrix) }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::522922866161:role/tfg-repo-base-cicd

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: $TF_VERSION
      
      - name: Setup Terragrunt
        run: |
          curl -s -qL -o terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/${{ env.TG_VERSION }}/terragrunt_linux_amd64
          chmod +x terragrunt
          sudo mv terragrunt /bin

      - name: Terragrunt init
        id: init
        run: terragrunt init -input=false -reconfigure --terragrunt-working-dir ${{ matrix.dirs }}

      - name: Terraform apply
        id: apply
        run: terragrunt apply -auto-approve -input=false --terragrunt-working-dir ${{ matrix.dirs }}