name: 'Validate'
on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents:  write

env:
  TF_VERSION: '1.5.7'
  TG_VERSION: '0.58.2'
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  Set-up:
    name: Setting up environment
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check out base ref
        run: |
          git fetch --no-tags --depth=1 origin $GITHUB_BASE_REF
          git fetch --no-tags --depth=1 origin $GITHUB_HEAD_REF

      - name: Get working directory
        run: |
          CODE_DIR=$(git --no-pager diff --diff-filter=d --raw --name-only origin/$GITHUB_BASE_REF origin/$GITHUB_HEAD_REF | egrep -E "\.tf\$|^\/dev|^\/staging|^\/prod" | grep ".*\/" -o | uniq)
          echo "WORKING_DIR=$CODE_DIR" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: $TF_VERSION

      - name: Install Terragrunt
        run: |
          curl -s -qL -o terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/$TG_VERSION/terragrunt_linux_amd64
          chmod +x terragrunt
          cat /bin/terragrunt
          sudo mv terragrunt /bin
      
      - name: Verify Terragrunt version
        run: terragrunt --version

      - name: Verify Terraform version
        run: terraform --version
      
      - name: Verify awscli version
        run: aws --version

      - name: Terragrunt Format
        id: fmt
        run: |
          terragrunt fmt -check -recursive --terragrunt-working-dir ${{ env.WORKING_DIR }} -diff
        continue-on-error: false

      - name: Terragrunt Validate
        id: validate
        run: terragrunt validate --terragrunt-working-dir ${{ env.WORKING_DIR }} 
        continue-on-error: true