name: Validate
on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  id-token: write
  contents: read  
  pull-requests: write

env:
  TF_VERSION: '1.5.7'
  TG_VERSION: 'v0.58.2'

jobs:
  detect-folders:
    runs-on: ubuntu-latest
    name: Detect folders to apply
    outputs:
      matrix: ${{ steps.detect-folders.outputs.all_changed_files }}'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get all changed directories into matrix
        id: detect-folders
        uses: tj-actions/changed-files@v44
        with:
          dir_names: 'true'
          matrix: 'true'
          files: |
             **.tf
      
      - name: List all changed folders
        run: echo '${{ steps.detect-folders.outputs.all_changed_files }}'

  terraform-validate:
    name: Terraform validate
    runs-on: ubuntu-latest
    needs: detect-folders
    strategy:
      fail-fast: false
      matrix:
        dirs: ${{ fromJSON(needs.detect-folders.outputs.matrix) }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::522922866161:role/tfg-repo-base-cicd

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: $TF_VERSION

      - name: Verify Terraform version
        run: terraform --version

      - name: Setup Terragrunt
        run: |
          curl -s -qL -o terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/${{ env.TG_VERSION }}/terragrunt_linux_amd64
          chmod +x terragrunt
          sudo mv terragrunt /bin
          terragrunt --version

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - name: Terragrunt Format
        id: fmt
        run: |
          terragrunt fmt -check -recursive --terragrunt-working-dir ${{ matrix.dirs }} -diff
        continue-on-error: false

      - name: Terragrunt Validate
        id: validate
        run: |
          cd ${{ matrix.dirs }}
          terragrunt validate

      - name: TFSec
        id: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
        with:
          tfsec_args: --tfvars-file ${{ matrix.dirs }}/terraform.tfvars -m CRITICAL
          soft_fail_commenter: true
          working_directory: ''
          github_token: ${{ secrets.GITHUB_TOKEN }}